### ISSUE TITLE
Perl 5.22.1 and 2Checkout Compatibility

### ISSUE THREAD

**Issue by bignmllc** [vampirechicken/VendorAPI--2Checkout--Client#1]
Hi, I found this at MetaCPAN, which directed me here. I have a client with a very old Perl website using 2Checkout, but his code he has is having problems. I would like to use this Package if you think it will work with Perl 5.22.1 (the CPAN tests seem ok), and if it will still successfully work with 2Checkout's API interface. Thanks for your help. Tom Straub

**Comment by vampirechicken** [comment]
Haven't worked at 2co in several years, so I have no idea. Sorry.
